version: v1alpha1
debug: true
persist: true
machine:
  type: controlplane
  token: 9p8as7.86rd3ce7vzj6tprk
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBMVcvaStqYSs1Umk4ekxOZkhxOXpBVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOekkzTURFMU9ESTBXaGNOTXpRd056STFNREUxT0RJMFdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUdUZURjUmRxWEdKTHFzSHZRN1BWbWdJZUJEYTBEREhMN1JmClJ0b3hIdTFybzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJoam9DZEFQdTRUUzE4bwpPemJkQlIrQW1BV2xNQVVHQXl0bGNBTkJBUFdyV2w4QnR4ZG91ejEzMXN2aTBuWGc0ZFZXbmpKM0xyV092M3JHCmczM3lFc1ZsZ2ovSHZGVjQydTRZZWVGL0VNcUNhYzRVOGRzeVJqa2FCYzVHckFBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJRGgyOG1xenFxWnA4ckdhekFhYjhXZUdPRlA1eWVXdWgvcDh5NmZCVVh5eAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  certSANs: []
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.30.3
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    extraArgs:
      rotate-server-certificates: true
  network:
    interfaces:
      - interface: enp1s0
        vlans:
          - vlanId: 1
            addresses:
              - 10.10.9.31/23
          - vlanId: 30
            dhcp: true
          - routes:
              - network: 0.0.0.0/0
                gateway: 10.10.8.1
              - network: 172.16.10.0/24
                gateway: 172.16.10.1
    nameservers:
      - 10.10.8.1
      - 172.16.10.1
  install:
    disk: /dev/nvme0n1
    image: ghcr.io/siderolabs/installer:latest
    wipe: true
    extraKernelArgs:
      - talos.platform=metal
      - reboot=k
  registries: {}
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
  nodeLabels:
    stack: homeassistant
  disks:
    - device: /dev/sda # The name of the disk to use.
      partitions:
        - mountpoint: /var/mnt/local # Where to mount the partition.

cluster:
  id: e8hYKKpZgDi2fMeB-zAMHOk8_-FqAf2dMSJdBlnTpGw=
  secret: MdiCB5E0j3tXEQwKO0euGpkz1i5EgV9/jPiVqZfc908=
  controlPlane:
    endpoint: https://10.10.9.31
  clusterName: homeassistant
  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: aphnch.30a50pn2z4w2afbi
  secretboxEncryptionSecret: fK81upWc0IHZhot9dzz1OEjNT6ug40yWmsl13d0gXds=
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUxvbDlmZXlPcUZabGdIbVFGQkpzWXd3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOREEzTWpjd01UVTRNalJhRncwek5EQTNNalV3TVRVNApNalJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVFjRHB3YVVHT21IR3BzTUlBV29BaWk4VWpHUXF3eDJFTk10Rlo0dmFveERIdzlRYXgrSEp1UnVuT3AKa2RFcnAxei8rWnVuTDAwTW8xZ0tCUkdRcDlmRW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTzN2YXN6V0lUWk85MUxXYWp4dU1TV2ZUaGlCTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEQUpidkUKaTZsZWZsbEwvVXNPT0VHVmFkbWtUK3ZYQWo2Q21QSVVyL2JmWlFJZ2NGQzJXOWJPSUJ1a0NoTzFyK0RjOEJ2bgpVT3BBL0Q1ZHdzNjI0cE1yZDRnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVzSkllenhZbWtCN21zM1I5ZjkvYUZyU0FvWnNDcVlOekNzRWs4UWlCUW9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSEE2Y0dsQmpwaHhxYkRDQUZxQUlvdkZJeGtLc01kaERUTFJXZUwycU1ReDhQVUdzZmh5YgprYnB6cVpIUks2ZGMvL21icHk5TkRLTllDZ1VSa0tmWHhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  aggregatorCA:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYakNDQVFXZ0F3SUJBZ0lRUGo4SFhTMHZmQmtIVFVFaTR0cno0akFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJME1EY3lOekF4TlRneU5Gb1hEVE0wTURjeU5UQXhOVGd5TkZvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCTUJCMkZjVFRHQTFRYmxrSERvelVHZS9sbzZnQ0J6aFF5TlVMYVIvaGREblA1emZ5QjVxCkpQbForWTk3V3ZwSVNzSkhBeWpFOHk5TG9zRnBVamVFTWhhallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVqUDd2M0VuWHFrTjFZdFdIaEpaYzFYKzBkSGd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnClRYZmFNNzNSb2FrTGF2SDV6STkzd2dFditTZHpCeWxmeFl5ckFaR0tZODhDSUVVbVAxMklaNGRYRE5kVjRnYXcKSUQ1MVdOYnYvdWpOL3Z1a1V3VUlaekpwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNhcUpGa09LMlM5bHdnR0FPWDlFWTNDMEZiZEVzNW16MzVWRVZBWXp6YUtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFd0VIWVZ4Tk1ZRFZCdVdRY09qTlFaNytXanFBSUhPRkRJMVF0cEgrRjBPYy9uTi9JSG1vaworVm41ajN0YStraEt3a2NES01UekwwdWl3V2xTTjRReUZnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  serviceAccount:
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBekxIWmt0cGEzbVJURWJPcEhsblNSZmFCUUg4c0pjNWJZZW9TMWFtd0NZWmZzSlRlCnh3M0N3OFFpZVFxSkdIUzladmljYXVkdGZCVTdCa2dtVTVWOXFJYm03QWJGNjVpb2lsUExJcWc0WEc0N3A3dnAKRHIraXFRZEQyZ3dKc1RLS1lEd3d6bDZSNkExc2xVZ29iaDhCUFJYYldsS3h2OFdEdU8yNVExaWp1OWNUOEFoTApwdWdEZFhOQVF0M1lLdEFrNXgrM3JkU0RXc2dQZTlaQVZKbFJTT2dTeXRkV3N0Qno1VlBDNkV3WFQ1bmlPN1dQCndCQkxyNGpxbC9WWDZKa3lLTk5pTUNlSFl4MVZzbTZBWUpnVXAyVUhzUmIyRFArY0pkK3lvaUw5RzBYRm15clkKVUFmLzlDNUl3aUc5T2w1SWdvMU15ZWo1NmYxQjNwR1RxTjIySjI3cHk2a1BKOWdJaE1EbUhIeWx4Z3RWbkZjbgpZS2U4UkNBUHV3bWhZNlRRdHV4NDJ2aUlGVnBSZngvMWVlMTVTYXZ5alpNL1lUQWtQa1I5emdBLzhoeDhNMXVICmo4N1Q2bDRFc2Rvc0xURzFyd3k2RCtXSUJtMWhLYyt5bTBsSXp5RFpEM0pPb2U1ck0vWk5NbzNyL0FqWk9sZDcKTTN1V0g3M3ZqU2llQkxZOXluYjJKcTNSRTNIanBOQURJS2prelJoSGJMRHQvOFM4U1VEdzI5Z3B3dnhmaDRRNAp5a0VzRmdBZW4wQjZPWlNBMUcrL1k5cnFGVFk3N1Z4aS9VUnd0ZlFjR0h1S3JJTkhwd09lZ3RtL2J4dDYvNllLCnEveWNHNGUwbmZsQmQrUytMUVZlWEVKTE1NTGRUUFl2TVplT1NWSDhDOVhjMTJhMWQrcXkxMW1WUWVVQ0F3RUEKQVFLQ0FnRUFxQm9Dd1V4YlJib0VVa3hHUGV1citOTG84TXUvdU1pUVdZZitzY05xRTFoc0t6c0cvVmU2dEVUVgp2cXU5VFAxS01rOUhQYkFUUk15MnJZRUJJTEZyQWNUUHpkUCtKRzQ1TTJoL01WWU8rekY0QWxjYW5ZY1prVkNyCkUxM0JjK2s2cEsrcHNVRU8rQkJXTlA2T1hXbE8vaGgrRE41T3BWd1N3Z05RbXhNblcvTFVwOUpZTnBqaGhrb0EKNHlrSEJwbnJSSGZTdzRuNzJjamtsbUdzY1ExOEtMQ1dCa2owSldOMVdrY0FrUDgwUWFYeG1mR1FQVDNrdWlKcAo3aU9KYnphb2I4aXhJVFRGUmN0b2ZtR3JRaWlEQmJtOXFGeGY4dXJVRkhKeVpCN3gxN3pqL0hzaUxBOTF6dFZYCjRUNE9CZW82Q0NUOGcvQzFsTWpzbUZqYmQ5bWtaYUhOd3cyY25KT05kcmRkL09QTE9mL1kycm4rdEZXNXVqUmoKdlArYWM1YzFpcmphQzcva1hxZ1o0eFBWNjd2N3ZINTUxc3pINlVHSXN1ZlBTcEoyQWVVWVYyZHVUc2t4Z240Zwo0anhXQnIzZUpVQWI0ODRpK0dqMzAxNGJYNGhZNndjaWJleHhIc01GL0kzQTZYY3V3NUhROGJUcElXT3J1dXp4CkYyREtDbEYyWE5xK0F3cWNKRThNR0xmQzdrTFhTZ2V3eDFEaFIzdzhvUmtxZ1M5UHI4UmREdnJncXZzMzlESU0Kc05jb3lhTWh2MUxGTEV6RU1POFNJVDRaUndMUVR0MWwwTkczM1dkeHpiajBPSlY3OHpXUWp5YTY0VGhKbEdkYQowb0ZENGRPbGkyUVJtc0p1ZUNpV1NnMjF2VWZjL1JsYW9JZmNZaTlEU29PbHFDYzg5cjBDZ2dFQkFQNzlxYk9jCm9zN0NSQ3RINkJMelZmZE03SHNEOVpyWUN3cStrTTVMNWN1RkR0R3l1aUlFQ2s2TXh2OHlHUEVIcVBMbHk5bUIKZTZCNjZkSXlXbjV0ZjJIdWIva3UyMmticXpId3VPRXBBZ3ZnUkFKU0NOOXZLdnJ2WVlFdVZVZzV2TDdVdXJEeQpEeUpJMmoveWlMOUFDMTViaStvYm9lQW0xNVRuNnFaYjc2S3B1WUx5U05ETi9yeEE4dUJWQ3hMeXkrZ203dEFrCmJHRDltcm9lVy9nS0dPeDNDQXFJd1REQVk5dTN1SUNCWDFuYWVzbGkyRnViYVF1K0tvVWR5UFNaNm5IWXZsNU4KUzVuRmRIMW5RRHhzZGdwMCtXZ3ZtNjZad29VNVViYllUVkFMSllXZXc5WFYyNFE0MzNvSk9DeXNBYU1KNlcrNwp1aDNJUHpBSk1KdTZPYU1DZ2dFQkFNMkJPeGNqcCtmSW5ndStGT1cxU0g2SE1EU2FRMEFvSnFmdnliT2EyR1pxCmJVVDcrb1VUQldxeVBBK0FlSnBGcFpvZDNvMUNvdXVlaFYvT0pObVU1YktpRDhaVzFGOTZUeHV6Rnh2Z1YwMk8KU0xQRUVpNjFrQUVlbXBLOWtuS0NTcXFZSTZlTmR2QVcvbkRnM2Z4YUgrVTFKR0p5eWRSOUNpUklZalRIQXc1eQpsOW9jbnR4RTV0N0NKRFpISEU3SkRUMjNtSzdBT1FOMmpEYlVSdHIzM3ZrcDFPcXkvV2dQUlN1cm9pZ3hsWlFzCnlteVhZeWhiSkFpU2dlc1J0dkcwekFZaEdEaERVdGgrV25KaHFYT2ZDNUpWeGZtZVk5R1ZxdStqMlFoWXBZUFoKbXJscWxVbjQrZDMrSUtyWURhQURSK1ZTMDBES2luM0FDbVE4Yzg4M1h0Y0NnZ0VBUU1NaVI4ai9uSzNBYkpHdAp3cXBrNmhOeWVHZndDQ3pZMlJpL1pIWG9Ya0ZrR3lSZW0rY1V5eEI4TmpKK0hUR0oybTg4ei9oUDh0bGs2NHI0CmF1WGFsWC9lbHBZdENjd0tOZnZpcU9VbWJPZS92aXNocjhYblQ2WmV5RldCT1gvWWpVc3dRMktuTDFqN2ZZUlcKOE9RT1B4L1hNRlZtVHF6dTBoWDVCZG1SeW1sN0FXUVIxRjZOVlRqVnR0NUNtc1JwdjRPcjRkZHVZMC9sN1dGcQprRnZZS3E2c3J5ZytrT2c4TklDNzduOXRQVC85TVlyV1VxWHREeHQwWnl6Q2JrVnRRdzcrZ3FyMUNaQVozd1BMClQ4MW9TWTJlRHJVUXdFNnpGZTBSOFBPTTUwaDlkaXQxcDZqU1FRbkUwSlRvM0lldlByNTB1SGtnY3hINTRuUmoKRVJwQ0t3S0NBUUJTZ0J6K3p4dXJHNGtIWWNuMTVlOHlqSWMzdHU1a3BUblBsWjQ5OGw0Sno1UUthN1pKRWpmTQplNzFNNCtDRzNvcjY4aDdVU3ZvbzZUeldGMllIeTVUalA5aGhZWjVrcmk5d0NWZXZvMEtwS2dQWjEwOE5YV3B3CmFKN1paaTJTdHVmTzBNRVBsT1U0d2FKb0luNDd2dHFySThoMWxXdWRXSTFudjM5ZGZMK25YeTNETEZaQ1M0NzcKd3FqUytYMU55N3o3RitlOTBBR1RlRllWOU9aMUphbG9FZmtlTjdrdnUyR2poSVhXNlFFSnVXbVNhcnd1Q1ZqUAo4REVqODdxa0VsY041dDlZUnY3TlZ2eHNpdlNDTEVseTkraEFxK3VheWlFVGo0MmpvaUxnYWMySnZsWXNtajJGCmQyNFo2QjZnTEhFQ2lWdXgyUjM4R2NxU0x3cTNGNTJGQW9JQkFEdEU4bTNZeWxyalhrZWwyTFArNlFXR3lETTkKejFvakNJamE3dzFqMWttTnZMSmh4QVM5ODVZUC9kanUrQStrMGtCaTdKakN0NjlYVzZpbkdjdzl4UmdFdXNuZwp2K1MyMDFBdWh1SXFqelJCMG9kcWMvYVpXbjFGWWdkZHN5b0VFTHl3cENxamlIbEIxL1Z5cUJUUXBDbTYxdmpFClo1bENYVjF0ZHdEVnJEL2prNDYxeitVdjc2Tmx3K3dEWExFMTQrTUUvNnlSZ01RYVo1R2pEejQ3MUVzdVlMRisKbFBtT01FcFFIbE4xT2xMMlA2Wktlajk2dS8wWGtFTFV1UnJ5VXNjOXhvcEk3ak1FRmlmcS9HL2l1a1RsN3lLRgowb3BZL1F5Rnl4OStVQjNoTVYyYnRZWld4R1padUNSZmlaMHRtNWpjalVVT2xRdVJuOFBzZW5aaW5Sbz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.30.1
    certSANs:
      - 10.10.9.31
    disablePodSecurityPolicy: true
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            #            enforce: baseline
            enforce: privileged
            enforce-version: latest
            warn: restricted
            warn-version: latest
          exemptions:
            namespaces:
              - kube-system
            runtimeClasses: []
            usernames: []
          kind: PodSecurityConfiguration
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.30.1
  proxy:
    image: registry.k8s.io/kube-proxy:v1.30.1
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.30.1
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
  etcd:
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQU1JbGU3YWZ5R21NRG13bGdsOVRobmt3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TkRBM01qY3dNVFU0TWpSYUZ3MHpOREEzTWpVd01UVTRNalJhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRaDZwQTAvcElpCnp2dkRSQjJQRFJNTmRuczl5Ry9GbER6TU9vNEpXc2FadFBBM1ZmclVOdFZDWHJxRkIzd1BlSEttbGUyZmZvc2EKazFjUDd6bzM3WGhibzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkxGMUxWT2dQSDArCmUyc05mWC80d3dkUGl4MmdNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJQmlhTXNBTzlLcS8xMWNuOHdlVkJJd3IKaWFTVGN0OHI1RStaZGRaclRpdEpBaUVBbWIwZTh4OHFLcTRkUGloTCtKQW51cTFrdEdUMm1zaEJ1SktkS2dDcAowQTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdrSUNoZ2sxL2xjeXRxS0pkZ0FOb2xiTzJ1YWpyck1EK0tORTVkeGFyTlBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSWVxUU5QNlNJczc3dzBRZGp3MFREWFo3UGNodnhaUTh6RHFPQ1ZyR21iVHdOMVg2MURiVgpRbDY2aFFkOEQzaHlwcFh0bjM2TEdwTlhEKzg2TisxNFd3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  inlineManifests: []
  aescbcEncryptionSecret: z01mye6j16bspJYtTB/5SFX8j7Ph4JXxM2Xuu4vsBPM=
  allowSchedulingOnControlPlanes: true
