apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hass-stack/home-assistant/
#  - nfs.yml
#  - metallb/
  #- hass-stack/zigbee/
  #- hass-stack/zwave/
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ha-test.sancaktar.net
    target:
       kind: Ingress
       name: home-assistant
       version: v1
#- patch: |-
#    - op: replace
#      path: /spec/addresses/0
#      value: 10.1.1.10/32
#  target:
#    kind: IPAddressPool
#    name: iot
#- patch: |-
#    - op: replace
#      path: /spec/addresses/0
#      value: 192.168.1.10/32
#  target:
#    kind: IPAddressPool
#    name: lan
#- patch: |-
#    - op: replace
#      path: /spec/loadBalancerIP
#      value: 10.1.1.10
#  target:
#    kind: Service
#    name: ingress-nginx-controller
