allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
mountOptions:
- vers=4.1
provisioner: cluster.local/nfs-server-provisioner
volumeBindingMode: Immediate

